      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "=== Cleaning repo and pulling latest code ==="
            cd ~/PublicHealthDomain

            # Fix permissions to avoid 'git clean' errors
            sudo chown -R ec2-user:ec2-user logs || true
            chmod -R u+rw logs || true

            # Remove stale git lock file if exists
            rm -f .git/refs/remotes/origin/main.lock || true
            git remote set-head origin -a || true
            git fetch --prune origin || true

            git reset --hard origin/main
            git clean -fd

            echo "=== Removing old container ==="
            docker rm -f health-app || true

            echo "=== Cleaning dangling Docker images to free space ==="
            docker image prune -af || true
            docker volume prune -f || true

            echo "=== Building Docker image ==="
            docker build --no-cache -t public-health-app:latest .

            echo "=== Running new container ==="
            docker run -d --name health-app -p 8000:8000 public-health-app:latest

            echo "=== Ensure logs directory exists inside container ==="
            docker exec health-app mkdir -p /app/logs

            echo "=== Sync logs to S3 ==="
            docker exec health-app sh -c "aws s3 cp /app/logs/ s3://jenkins-artifacts-logs/logs/ --recursive"

            echo "Deployment complete!"
          EOF
