name: Deploy to EC2 and Sync Logs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Go to app directory
            cd ~/PublicHealthDomain

            # Ensure latest main branch
            git reset --hard
            git pull origin main

            # Build Docker image
            docker build -t public-health-app:latest .

            # Stop & remove old container safely
            echo "Checking existing containers named health-app..."
            docker ps -a --filter "name=health-app"

            echo "Stopping container if running..."
            docker stop health-app 2>/dev/null || echo "Container not running."

            echo "Removing container if exists..."
            docker rm health-app 2>/dev/null || echo "Container already removed or does not exist."

            echo "Listing containers again..."
            docker ps -a --filter "name=health-app"

            # Run new container with volume mount so future changes persist
            docker run -d --name health-app -p 8000:8000 -v ~/PublicHealthDomain:/app public-health-app:latest

            # Ensure logs folder exists inside container
            docker exec health-app mkdir -p /app/logs

            # Sync logs to S3
            docker exec health-app sh -c "aws s3 cp /app/logs/ s3://jenkins-artifacts-logs/logs/ --recursive"

            echo "Deployment complete!"
          EOF

      - name: Confirm deployment
        run: echo "Deployment complete. Your EC2 instance has the latest changes."
