name: Deploy to EC2 and Sync Logs 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            set -e

            echo "=== Cleaning repo and pulling latest code ==="
            cd ~/PublicHealthDomain
            rm -f .git/refs/remotes/origin/main.lock || true
            git remote set-head origin -a
            git fetch --prune origin
            git reset --hard origin/main
            git clean -fd

            echo "=== Stopping old container if running ==="
            docker stop health-app || true

            echo "=== Removing old container if exists (force remove) ==="
            docker rm -f health-app || true

            echo "=== Cleaning dangling Docker images and volumes ==="
            docker image prune -af || true
            docker volume prune -f || true

            echo "=== Building Docker image ==="
            docker build --no-cache -t public-health-app:latest .

            echo "=== Running new container with AWS credentials ==="
            docker run -d --name health-app -p 8000:8000 \
              -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
              -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
              -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
              public-health-app:latest

            echo "=== Ensure logs directory exists inside container ==="
            docker exec health-app mkdir -p /app/logs

            echo "=== Sync logs to S3 with explicit AWS credentials passed inside container ==="
            docker exec health-app sh -c "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} aws s3 cp /app/logs/ s3://jenkins-artifacts-logs/logs/ --recursive"

            echo "Deployment complete!"
          EOF

      - name: Confirm deployment
        run: echo "Deployment complete. Your EC2 instance has the latest changes."
