name: Deploy to EC2 and Sync Logs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/PublicHealthDomain
            git reset --hard
            git pull origin main

            # Build Docker image
            docker build -t public-health-app:latest .

            # Stop & remove old container if exists
            docker stop health-app || true
            docker rm health-app || true

            # Run new container
            docker run -d --name health-app -p 8000:8000 public-health-app:latest

            # Ensure logs folder exists inside container
            docker exec health-app mkdir -p /app/logs

            # Sync logs to S3
            docker exec health-app sh -c "aws s3 cp /app/logs/ s3://jenkins-artifacts-logs/logs/ --recursive"
          EOF

      - name: Confirm deployment
        run: echo "Deployment complete and logs synced to S3."
