name: CI/CD Pipeline (Build & Logs)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: jenkins-artifacts-logs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t public-health-app:${{ github.run_number }} .

      - name: Run Container
        run: |
          docker run -d -p 8080:8080 --name health-app public-health-app:${{ github.run_number }}

      - name: Wait and Capture Logs
        run: |
          sleep 5
          docker logs health-app > app.log

      # Configure AWS CLI before any aws commands or S3 uploads
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload Logs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: .
          DEST_DIR: logs/

      - name: Upload Artifacts to S3
        run: |
          mkdir -p build
          cp -r * build/ || true
          aws s3 cp build/ s3://${{ env.S3_BUCKET }}/artifacts/${{ github.run_number }}/ --recursive

      - name: Cleanup
        run: |
          docker stop health-app || true
          docker rm health-app || true
